spring:
  datasource:
    url: jdbc:mysql://194.59.164.22:3306/u413457129_povioTestDb
    username: u413457129_povioTestUser
    password: Moonchild986
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true